[package]
name = "ftswarm_proto"
version = "0.1.0"
edition = "2021"

[[example]]
name = "proto_command"
path = "examples/proto_command.rs"

[[example]]
name = "proto_messageparser"
path = "examples/proto_messageparser.rs"
