[package]
name = "ftswarm"
version = "0.1.0"
edition = "2021"
description = "A simple swarm protocol communication library"

[dependencies]
ftswarm_proto = { path = "../ftswarm_proto" }
log = "0.4.21"
async-channel = "2.2.0"