[package]
name = "ftswarm"
version = "0.1.0"
edition = "2021"
description = "A simple swarm protocol communication library"

[dependencies]
ftswarm_proto = { path = "../ftswarm_proto" }
log = "0.4.21"
serialport = "4.3.0"
tokio = { version = "1", features = ["full"] }
rand = "0.9.0-alpha.0"
